apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    jsonData:
      httpHeaderName1: X-Promtail-Token
    secureJsonData:
      httpHeaderValue1: 8cf42e37b1bd4483b816be0d3f832ccb

  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    jsonData:
      httpHeaderName1: X-Promtail-Token
    secureJsonData:
      httpHeaderValue1: 8cf42e37b1bd4483b816be0d3f832ccb
